### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by anti199994** [FingerRec/Self-Supervised-Temporal-Discriminative-Representation-Learning-for-Video-Action-Recognition#1]
Hello, how is the data list generated?

**Comment by anti199994** [comment]
How is this data list generated? Can you share the code @FingerRec

**Comment by FingerRec** [comment]
Sorry for the late reply.
1. For UCF101/HMDB51, the data list is in format of [imgs_dir, frames_len, class]; 
Please download these datasets include splits from the official website and extract frames with ffmpeg/opencv.
The generated step should be quite easy and more details can be referred to [tsn](https://github.com/yjxiong/temporal-segment-networks) section Construct file lists for training and validation.
2. For Kinetics, the set is large and the extracted frames will excel 1.5T. So we load and decode video on the fly by lintel for fast IO. The data list is in the format of [video_path, class];
