### ISSUE TITLE
pretrained Self Supervised weights

### ISSUE THREAD

**Issue by jaypatravali** [FingerRec/Self-Supervised-Temporal-Discriminative-Representation-Learning-for-Video-Action-Recognition#2]
Hi i am interested in running the pretrained model from self supervision.
Could you please provide the weights?

**Comment by FingerRec** [comment]
No Problem!
I'm a liitle busy these days.  I will upload the pretrain model from the server in a few days as far as possible.  
Besides, I plan to update this Code recently. 
let me know if you have any other problems in reproducing any result reported in our paper.
:)

**Comment by Mrbishuai** [comment]
我可以能问您一下 视频是怎样生成图片帧的 我想自己生成list并做自监督训练

**Comment by anti199994** [comment]
Hello, I'm training the pretrained model by myself. What's your final loss and prob? thanks@FingerRec

**Comment by anti199994** [comment]
> No Problem!
> I'm a liitle busy these days. I will upload the pretrain model from the server in a few days as far as possible.
> Besides, I plan to update this Code recently.
> let me know if you have any other problems in reproducing any result reported in our paper.
> :)

Hello, I'm training the pretrained model by myself. What's your final loss and prob?

**Comment by FingerRec** [comment]
Hi, everyone.  Really sorry for late reply, the readme is update now!

@jaypatravali  I have provided the self-supervised pretrain model in google driver. Look Readme for details.

@Mrbishuai 使用ffmpeg或者opencv 抽帧. 详细看dataset.md

@anti199994 loss is 0.2 and ins_prob is 12.41, look readme for details.

**Comment by NadineBehrmann** [comment]
Hi, 
thanks for uploading the self-supervised pretrained weights! Unfortunately, the provided link asks for access rights. Could you please make them available? 
Thank you!

**Comment by FingerRec** [comment]
@NadineBehrmann try it again

**Comment by NadineBehrmann** [comment]
It works now. Thanks a lot!
