### ISSUE TITLE
How to get the small scale of data

### ISSUE THREAD

**Issue by BestJuly** [FingerRec/Self-Supervised-Temporal-Discriminative-Representation-Learning-for-Video-Action-Recognition#4]
Hi, thank you for the nice work.

I am interested in the small-scale video dataset part. I think this is a subset of original dataset such as UCF101.
Is the data sampling part totally random? For example, in the figure, it plots the dot of results with 1000 samples. Therefore, does this 1000 samples are randomly sampled frorm UCF101 full dataset? Or maybe you just set that for each action, 10 videos are selected to form 1010 samples for training. I do not know the inflence of these two sampling methods, but the latter one is more balanced.

I would also appriciate it if you can provide the corresponding training list. Thank you.

**Comment by FingerRec** [comment]
It is a good question.

Both UCF/HMDB contain thousands level video, to explore the influence of more data. We sample different amount samples in Kinetics in class-balanced way as previous method like S3D. What's need is to define the sample radio and generate train list. Please look [gen_sub_dataset.py](https://github.com/FingerRec/Self-Supervised-Temporal-Discriminative-Representation-Learning-for-Video-Action-Recognition/blob/master/src/utils/data_process/gen_sub_dataset.py).

**Comment by BestJuly** [comment]
Hi, @FingerRec . Thank you for your instance response.

It seems I misunderstand some parts of this part and I thought it is something like pretraining on large dataset and finetuning on small scale data (which is something like semi-supervised learning in SimCLRv2). I did not look carefully about that part especially the figure because UCF101 does not contain more than 15,000 videos. Sorry for that.

Anyway, you have solved my problem and I will follow your instructions. Thank you.
