### ISSUE TITLE
What's the finetune feature?

### ISSUE THREAD

**Issue by June01** [FingerRec/Self-Supervised-Temporal-Discriminative-Representation-Learning-for-Video-Action-Recognition#7]
Hi, thanks for making the code public. I am wondering what's the finetune feature? Which dataset it is finetuned on? Actually I am planning to use self-supervised pretrained feature (not finetune on anything), would you like to do me a favor to post the link again 1) the weights from self-supervised pretrained on Kinetics-400; 2) the weights pretrained from both kinetics-400 and ucf-101? Any feedback is appreciated! Looking forward it!

**Comment by FingerRec** [comment]
Sorry for late reply!
We pretrain on UCF/Kinetics, than fine-tune on small-scale dataset like UCF/HMDB51.
